### GET ALL
GET http://localhost:3001/api/blogs

### POST ONE
POST  http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Title",
  "author": "Author",
  "url": "http://sample.com/url",
  "likes": 0
}